---
- name: Exécuter un script sur un serveur distant
  hosts: all
  become: yes

  tasks:
    - name: Copier le script
      copy:
        src: ./insert_data_insee.py  
        dest: /scripts/insert_data_insee.py 
      become: yes

    - name: Extraire les secrets de Vault
      community.general.hashivault.read:
        path: /db_pass
        url: http://192.168.1.23:8200
      register: vault_secrets

    - name: Exécuter le script Python avec les variables de Vault
      command: python3 /scripts/insert_data_insee.py
      environment:
        MYSQL_HOST: "{{ vault_secrets.data.data.mysql_host }}"
        MYSQL_USER: "{{ vault_secrets.data.data.mysql_user }}"
        MYSQL_PORT: "{{ vault_secrets.data.data.mysql_port }}"
        MYSQL_PASSWORD: "{{ vault_secrets.data.data.mysql_password }}"
        MYSQL_DATABASE: "{{ vault_secrets.data.data.mysql_database }}"
        
    - name: Supprimer le script
      file: 
        path: /scripts/insert_data_insee.py
        state: absent
      become: yes
